pipelines:
  tags:
    'test-*':
        - step:
            name: Sync GitHub Mirror
            image: alpine/git:latest
            clone:
              enabled: false
            script:
              - git clone --bare git@bitbucket.org:i2tic/gauss_tag_gtm_config.git
              - cd gauss_tag_gtm_config.git
              - git remote add github-repo git@github.com:makingscience-gausstag/gauss_tag_gtm_config-alpha.git
              - git push github-repo master:main
